version: '3'
services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./src/:/var/www/
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-database}
      - DB_USERNAME=${DB_USER:-db-user}
      - DB_PASSWORD=${DB_PASS:-db-pass}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_HOST=db
      - PMA_USER=db-user
      - PMA_PASSWORD=db-pass
    ports:
      - 8888:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./src/:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-root}
      - MYSQL_DATABASE=${DB_NAME:-database}
      - MYSQL_USER=${DB_USER:-db-user}
      - MYSQL_PASSWORD=${DB_PASS:-db-pass}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT:-3306}:3306
