version: '3'

services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./src/:/var/www/
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-database}
      - DB_USERNAME=${DB_USER:-db-user}
      - DB_PASSWORD=${DB_PASS:-db-pass}
  
  # phpmyadminのコンテナ
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=db-user
      - PMA_PASSWORD=db-pass
    ports:
      - 8888:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
  
  # webサーバのコンテナ
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./src/:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app

  # データベースのコンテナ
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: db
    environment:
      - MYSQL_DATABASE=${DB_NAME:-database}
      - MYSQL_USER=${DB_USER:-db-user}
      - MYSQL_PASSWORD=${DB_PASS:-db-pass}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-root}
      - "TZ=Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Tokyo
    volumes:
      - db-volumes:/var/lib/mysql/
    ports:
      - ${DB_PORT:-3306}:3306

  # メールサーバのコンテナ
  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
volumes:
  db-volumes:
  maildir: {}